# Generated by Django 3.1.5 on 2021-07-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=100, verbose_name='Sigla')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('escudo', models.CharField(max_length=100, verbose_name='Escudo')),
                ('serie', models.CharField(max_length=1, verbose_name='Serie')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
            ],
        ),
    ]
